# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------
# Generated file, DO NOT EDIT
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------------------------

from msrest.serialization import Model


class Avatar(Model):
    """Avatar.

    :param image: The raw avatar image data, in either jpg or png format.
    :type image: str
    :param is_auto_generated: True if the avatar is dynamically generated, false if user-provided.
    :type is_auto_generated: bool
    :param last_modified: The date/time at which the avatar was last modified.
    :type last_modified: datetime
    :param size: The size of the avatar, e.g. small, medium, or large.
    :type size: object
    """

    _attribute_map = {
        'image': {'key': 'image', 'type': 'str'},
        'is_auto_generated': {'key': 'isAutoGenerated', 'type': 'bool'},
        'last_modified': {'key': 'lastModified', 'type': 'iso-8601'},
        'size': {'key': 'size', 'type': 'object'}
    }

    def __init__(self, image=None, is_auto_generated=None, last_modified=None, size=None):
        super(Avatar, self).__init__()
        self.image = image
        self.is_auto_generated = is_auto_generated
        self.last_modified = last_modified
        self.size = size
